version: '3'

services:

  nginx:
    image: nginx:latest
    ports:
      - "8082:80"
    links:
      - phpfpm:phpfpm
    volumes:
      - ./docker-utils/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker-utils/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker-utils/logs/nginx:/var/log/nginx
      - ./:/var/www/html
    command: bash -c 'useradd -u 1000 local; nginx -g "daemon off;" && service nginx start && nginx -s reload'


  phpfpm:
    build: ./docker-utils/php/
    links:
      - db:db
    depends_on:
      - db
    volumes:
      - ./docker-utils/logs/php:/var/log/php
      - ./:/var/www/html

  db:
    image: mysql:5.7
    ports:
      - "3308:3306"
      - "444:443"
    volumes:
      - ./docker-utils/databases:/var/lib/mysql
      - ./docker-utils/sqldump:/app/sqldump
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: globe_d8
      MYSQL_USER: globe_d8
      MYSQL_PASSWORD: globe_d8